### ISSUE TITLE
RepliesOKResponse missing properties

### ISSUE THREAD

**Issue by bjorndavis** [JamesMarcogliese/slack-api-csharp#2]
It looks like the only public property for RepliesOKResponse is `Ok` -- for example, returned when calling 

```var resp = await slackWebAPI.Channels.RepliesAsync(token: token, threadTs: ts, channel: chan)```

Unless I'm mistaken, according to the docs [here](https://api.slack.com/methods/channels.replies), shouldn't there also be properties related to `messages` and possibly `has_more`?

**Comment by bjorndavis** [comment]
Not sure if other responses are similar -- this is the first one I came across.

**Comment by JamesMarcogliese** [comment]
I took a look, it's a bit strange. The classes that were generated include a RepliesOKResponse which make up all of the returns and it's missing the fields you mentioned. There's another class called 
RepliesOKResponseModel in there also that has all the fields but doesn't seem to be referenced by anything!

**Comment by JamesMarcogliese** [comment]
I might just do a mass replace with the RepliesOKResponseModel reference instead as they're identical except for RepliesOKResponseModel being complete. 

EDIT: I lied, some of the responses are only supposed to return an OK message. Will need to compile a list of ones that do.

**Comment by JamesMarcogliese** [comment]
Did more digging, It appears the spec they provided for Channels.Replies is slightly incorrect. The below is the spec, it lists that the response object is the plain RepliesOKResponse yet the example lists it using the RepliesOKResponseModel class.

`        "/channels.replies": {
            "get": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "description": "Retrieve a thread of messages posted to a channel",
                "externalDocs": {
                    "description": "API method documentation",
                    "url": "https://api.slack.com/methods/channels.replies"
                },
                "operationId": "channels_replies",
                "parameters": [
                    {
                        "description": "Unique identifier of a thread's parent message",
                        "in": "query",
                        "name": "thread_ts",
                        "type": "number"
                    },
                    {
                        "description": "Authentication token. Requires scope: `channels:history`",
                        "in": "query",
                        "name": "token",
                        "type": "string"
                    },
                    {
                        "description": "Channel to fetch thread from",
                        "in": "query",
                        "name": "channel",
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Typical success response",
                        "examples": {
                            "application/json": {
                                "has_more": false,
                                "messages": [
                                    {
                                        "last_read": "1509484885.000082",
                                        "replies": [
                                            {
                                                "ts": "1509484424.000601",
                                                "user": "U2U85N1RZ"
                                            },
                                            {
                                                "ts": "1509484885.000082",
                                                "user": "U2U85N1RZ"
                                            }
                                        ],
                                        "reply_count": 2,
                                        "subscribed": true,
                                        "text": "This is a channel message",
                                        "thread_ts": "1485913694.000025",
                                        "ts": "1485913694.000025",
                                        "type": "message",
                                        "unread_count": 0,
                                        "user": "U2X9P5FEL"
                                    },
                                    {
                                        "parent_user_id": "U2X9P5FEL",
                                        "text": "This is a thread reply",
                                        "thread_ts": "1485913694.000025",
                                        "ts": "1509484424.000601",
                                        "type": "message",
                                        "user": "U2U85N1RZ"
                                    },
                                    {
                                        "parent_user_id": "U2X9P5FEL",
                                        "text": "This is another thread reply",
                                        "thread_ts": "1485913694.000025",
                                        "ts": "1509484885.000082",
                                        "type": "message",
                                        "user": "U2U85N1RZ"
                                    }
                                ],
                                "ok": true
                            }
                        },
                        "schema": {
                            "additionalProperties": true,
                            "description": "Verbose schema not yet ready for this method.",
                            "properties": {
                                "ok": {
                                    "$ref": "#/definitions/defs_ok_true"
                                }
                            },
                            "required": [
                                "ok"
                            ],
                            "title": "Default success template",
                            "type": "object"
                        }`

**Comment by JamesMarcogliese** [comment]
So in the end, there are several flavours of the RepliesOKResponse depending on the method. Since it'll take ages to go through every one I'll fix just this one for now. I'll fix any that I come across, and if you stumble upon another, either submit another issue here or make a pull request.

**Comment by JamesMarcogliese** [comment]
I've replaced the return object with the correct one.  Changed has been pushed. Newest version is 1.1.4.

**Comment by bjorndavis** [comment]
Looks like that's working now - thanks again!
